# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cometbft/blocksync/v1/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cometbft/blocksync/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.types.v1 import block_pb2 as cometbft_dot_types_dot_v1_dot_block__pb2
from cometbft.types.v1 import types_pb2 as cometbft_dot_types_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!cometbft/blocksync/v1/types.proto\x12\x15\x63ometbft.blocksync.v1\x1a\x1d\x63ometbft/types/v1/block.proto\x1a\x1d\x63ometbft/types/v1/types.proto\"\x1e\n\x0c\x42lockRequest\x12\x0e\n\x06height\x18\x01 \x01(\x03\"!\n\x0fNoBlockResponse\x12\x0e\n\x06height\x18\x01 \x01(\x03\"\x0f\n\rStatusRequest\".\n\x0eStatusResponse\x12\x0e\n\x06height\x18\x01 \x01(\x03\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\x03\"o\n\rBlockResponse\x12\'\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x18.cometbft.types.v1.Block\x12\x35\n\next_commit\x18\x02 \x01(\x0b\x32!.cometbft.types.v1.ExtendedCommit\"\xd5\x02\n\x07Message\x12<\n\rblock_request\x18\x01 \x01(\x0b\x32#.cometbft.blocksync.v1.BlockRequestH\x00\x12\x43\n\x11no_block_response\x18\x02 \x01(\x0b\x32&.cometbft.blocksync.v1.NoBlockResponseH\x00\x12>\n\x0e\x62lock_response\x18\x03 \x01(\x0b\x32$.cometbft.blocksync.v1.BlockResponseH\x00\x12>\n\x0estatus_request\x18\x04 \x01(\x0b\x32$.cometbft.blocksync.v1.StatusRequestH\x00\x12@\n\x0fstatus_response\x18\x05 \x01(\x0b\x32%.cometbft.blocksync.v1.StatusResponseH\x00\x42\x05\n\x03sumB8Z6github.com/cometbft/cometbft/api/cometbft/blocksync/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cometbft.blocksync.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cometbft/cometbft/api/cometbft/blocksync/v1'
  _globals['_BLOCKREQUEST']._serialized_start=122
  _globals['_BLOCKREQUEST']._serialized_end=152
  _globals['_NOBLOCKRESPONSE']._serialized_start=154
  _globals['_NOBLOCKRESPONSE']._serialized_end=187
  _globals['_STATUSREQUEST']._serialized_start=189
  _globals['_STATUSREQUEST']._serialized_end=204
  _globals['_STATUSRESPONSE']._serialized_start=206
  _globals['_STATUSRESPONSE']._serialized_end=252
  _globals['_BLOCKRESPONSE']._serialized_start=254
  _globals['_BLOCKRESPONSE']._serialized_end=365
  _globals['_MESSAGE']._serialized_start=368
  _globals['_MESSAGE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
